### PR TITLE
HTML5 & CSS3 : Positioning and Floating Elements

### PR DESCRIPTION
**Pull request by brugobi**
Hello @uryela, sorry for the last pull request message.
In this PR we create a clone of an Article from The New York Times website.
We use:

* HTML & CSS
* Flex for the main page and floating elements for aside bar.

Additional:
*Images are inside the image folder.
*CSS is in assets folder.

Thank you for the review.

Bruna & Jasem

### CODE REVIEW

**Comment by JasemDuncan** [comment]
3 PR - Position and Floating Elements
** First request.

**Comment by uryelah** [comment]
Hey Guys, I'll have to mark this code review request as invalid.
The Pull Request should have a meaningful title and description, not just on the comments.

Follow the model shown [in this link.](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
69548761-3a8d3600-0f98-11ea-9f19-14da361c12e2

Please edit your PR title and message and request again for a code review.

**Comment by JasemDuncan** [comment]
Hello @uryela, sorry for the last pull request message.
In this PR we create a clone of an Article from The New York Times website.
We use:

HTML & CSS
Flex for the main page and floating elements for aside bar.
Additional:
*Images are inside the image folder.
*CSS is in assets folder.

Thank you for the review.

Bruna & Jasem

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  Team👏👏👏

This project meets the requirements for approval @brugobi  and @brugobi.👌

**STATUS: APPROVED ✅**

However, to make your project look even more awesome kindly fix the bottom scrollbar issue on the webpage.


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
